name: stack
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - av==15.1.0
      - babel==2.17.0
      - bidict==0.23.1
      - bleach==6.2.0
      - cachetools==6.2.0
      - cffi==2.0.0
      - colorlog==6.9.0
      - comet-ml==3.52.1
      - comm==0.2.3
      - configargparse==1.7.1
      - configobj==5.0.9
      - counting-splatfacto==1.0.0
      - cryptography==46.0.1
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.3.7
      - docstring-parser==0.17.0
      - dulwich==0.24.1
      - embreex==2.17.7.post6
      - everett==3.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fire==0.7.1
      - fpsample==0.3.3
      - fqdn==1.5.1
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - grpcio==1.75.0
      - gsplat==1.4.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - imageio==2.37.0
      - iopath==0.1.10
      - ipykernel==6.30.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - lark==1.2.2
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lxml==6.0.1
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.4
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - msgspec==0.19.0
      - multiprocess==0.70.15
      - narwhals==2.5.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==1.1.5
      - nest-asyncio==1.6.0
      - nodeenv==1.9.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nuscenes-devkit==1.2.0
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.5
      - pathos==0.3.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - plotly==6.3.0
      - plyfile==1.1.2
      - portalocker==3.2.0
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycollada==0.9.2
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymeshlab==2025.7
      - pyngrok==7.3.0
      - pyquaternion==0.9.9
      - python-box==6.1.0
      - python-engineio==4.12.2
      - python-json-logger==3.3.0
      - python-socketio==5.13.0
      - pytorch-msssim==1.0.0
      - pyzmq==27.1.0
      - rawpy==0.25.1
      - referencing==0.36.2
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - rtree==1.4.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.38.0
      - shapely==2.0.7
      - shtab==1.7.2
      - simple-websocket==1.1.0
      - simplejson==3.20.1
      - six==1.17.0
      - sniffio==1.3.1
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==7.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorly==0.9.0
      - termcolor==3.1.0
      - terminado==0.18.1
      - tifffile==2025.5.10
      - timm==0.6.7
      - tinycss2==1.4.0
      - tinycudann==2.0
      - torch==2.1.2+cu118
      - torch-fidelity==0.3.0
      - torchmetrics==1.8.2
      - torchvision==0.16.2+cu118
      - tornado==6.5.2
      - traitlets==5.14.3
      - trimesh==4.8.2
      - triton==2.1.0
      - typeguard==4.4.4
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tyro==0.9.31
      - uri-template==1.3.0
      - vhacdx==0.0.8.post2
      - viser==0.2.7
      - wadler-lindig==0.1.7
      - wandb==0.21.4
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.11
      - yourdfpy==0.0.58
prefix: /home/vsw/miniconda3/envs/stack
