name: patch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accimage=0.2.0=py310hbd46f56_3
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - intel-ipp=2019.1.144=h711154d_3
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libjpeg-turbo=2.1.1=h7f98852_0
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.6.0
      - adeval==1.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - albucore==0.0.17
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - bleach==6.3.0
      - catalyst==22.4
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - clip==1.0
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configargparse==1.7.1
      - configmypy==0.2.0
      - contourpy==1.3.2
      - cython==3.0.0
      - dash==3.2.0
      - datasets==2.15.0
      - debugpy==1.8.17
      - decorator==4.4.2
      - defusedxml==0.7.1
      - diffusers==0.35.2
      - dill==0.3.5.1
      - docstring-parser==0.17.0
      - einops==0.8.1
      - ema-pytorch==0.7.3
      - exceptiongroup==1.3.0
      - faiss-gpu==1.7.2
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - freia==0.2
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - geomloss==0.2.6
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-slayer==0.5.0
      - idna==3.11
      - imageio==2.37.0
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lark==1.3.1
      - lightning-utilities==0.15.2
      - lit==15.0.7
      - llvmlite==0.45.1
      - loguru==0.7.3
      - mamba-ssm==2.2.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - multidict==6.7.0
      - multiprocess==0.70.13
      - mypy-extensions==1.1.0
      - narwhals==2.10.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - neuraloperator==0.3.0
      - ninja==1.13.0
      - noise==1.2.2
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==1.24.3
      - numpy-hilbert-curve==1.0.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - pastel==0.2.1
      - pathspec==0.12.1
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==9.4.0
      - pip==24.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - plyfile==1.1.3
      - poethepoet==0.10.0
      - pot==0.9.4
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pyarrow==19.0.1
      - pycocotools==2.0.10
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydeprecate==0.3.1
      - pyparsing==3.2.5
      - pypose==0.7.3
      - pyquaternion==0.9.9
      - pytest-mock==3.15.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytokens==0.2.0
      - pytorch-lightning==1.9.5
      - pytorch-metric-learning==2.9.0
      - pytorchcv==0.0.67
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - pyzorder==0.0.2
      - qudida==0.0.4
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - responses==0.18.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.1.3
      - scipy==1.10.1
      - send2trash==1.8.3
      - sentry-sdk==2.42.1
      - setuptools==75.1.0
      - shapely==2.1.2
      - shtab==1.7.2
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - statsmodels==0.14.5
      - stringzilla==4.2.2
      - super-image==0.2.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboardx==2.6.4
      - tensorly==0.9.0
      - tensorly-torch==0.5.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - test-tube==0.7.5
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.3
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.4.1+cu118
      - torch-fidelity==0.3.0
      - torch-harmonics==0.6.5
      - torchaudio==2.4.1+cu118
      - torchcde==0.2.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.4.2
      - torchprofile==0.0.4
      - torchsde==0.2.6
      - torchvision==0.19.1+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - trampoline==0.1.2
      - transformers==4.40.0
      - trimesh==4.9.0
      - triton==3.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.8.12
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yapf==0.40.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/vsw/miniconda3/envs/patch
