name: cst
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - blinker==1.8.2
      - cachetools==5.5.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - easydict==1.13
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - executing==2.2.1
      - faiss-gpu==1.7.2
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.57.0
      - ftfy==6.2.3
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.42.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.35.1
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipdb==0.13.13
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - knn-cuda==0.2
      - lazy-loader==0.4
      - lmdb==1.7.5
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nibabel==5.2.1
      - numpy==1.22.0
      - oauthlib==3.3.1
      - open3d==0.19.0
      - openai-clip==1.0.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.3.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyiqa==0.1.7
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scienceplots==2.1.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.43.0
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - stack-data==0.6.3
      - tb-nightly==2.14.0a20230808
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.5.4
      - tomli==2.3.0
      - torch==1.10.1+cu111
      - torchaudio==0.10.1+cu111
      - torchvision==0.11.2+cu111
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.22.3
      - warmup-scheduler==0.3
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - yacs==0.1.8
      - yapf==0.40.1
      - zipp==3.20.2
prefix: /home/vsw/miniconda3/envs/cst
