name: moc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.7.15=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - cachetools==5.5.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.1.3
      - easydict==1.13
      - einops==0.8.1
      - filelock==3.13.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - ftfy==6.2.3
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.4
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv-full==1.7.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.0
      - ninja==1.13.0
      - numpy==1.22.0
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - ordered-set==4.1.0
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.2.0
      - platformdirs==4.3.6
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.1
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - safetensors==0.5.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==59.5.0
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.0
      - tomli==2.2.1
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/vsw/miniconda3/envs/moc
