name: nerf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.0.1
      - addict==2.4.0
      - alphashape==1.3.1
      - annotated-types==0.7.0
      - anyio==4.5.2
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - av==12.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.5
      - bidict==0.23.1
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.1.8
      - click-log==0.4.0
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cryptography==46.0.1
      - cycler==0.12.1
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - diffusers==0.35.1
      - docstring-parser==0.17.0
      - embreex==2.17.7.post6
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - fire==0.7.1
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fruit-nerf==0.0.1
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - groundingdino==0.1.0
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.11.0
      - hausdorff==0.2.6
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - llvmlite==0.41.1
      - lxml==6.0.1
      - manifold3d==3.2.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - msgspec==0.18.6
      - narwhals==1.42.1
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==0.3.2
      - nest-asyncio==1.6.0
      - networkx==3.0
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.58.1
      - numpy==1.24.1
      - nuscenes-devkit==1.1.9
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.3.1
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - open3d==0.19.0
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.12.0.88
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.3.0
      - polyscope==2.2.1
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycollada==0.9
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyequilib==0.5.8
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymeshlab==2023.12.post2
      - pyngrok==7.2.12
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyransac3d==0.6.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-json-logger==3.3.0
      - python-socketio==5.13.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - rawpy==0.21.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.1.0
      - robust-laplacian==0.2.7
      - rpds-py==0.20.1
      - rsa==4.9.1
      - rtree==1.3.0
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - segment-anything-hq==0.3
      - send2trash==1.8.3
      - sentry-sdk==2.38.0
      - shapely==1.8.5.post1
      - shtab==1.7.2
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - supervision==0.18.0
      - svg-path==7.0
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.2
      - tinycss2==1.2.1
      - tinycudann==2.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.4.1+cu118
      - torch-fidelity==0.3.0
      - torchaudio==2.4.1+cu118
      - torchmetrics==1.5.2
      - torchvision==0.19.1+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - trimesh==4.8.2
      - triton==3.0.0
      - typeguard==4.4.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - tyro==0.8.12
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - viser==0.1.24
      - wandb==0.21.4
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wsproto==1.2.0
      - xatlas==0.0.11
      - xxhash==3.5.0
      - yapf==0.43.0
      - yourdfpy==0.0.58
      - zipp==3.20.2
prefix: /home/vsw/miniconda3/envs/nerf
